### ISSUE TITLE
`Move pydantic-settings to hell`

### ISSUE THREAD

**Issue by RoTorEx** [lubaskinc0de/clean-architecture#1]
Why did you decide to remove of pydantic-settings and use dataclasses?

**Comment by lubaskinc0de** [comment]
because pydantic-settings is a tool, which does unexpected thing like search .env in the parent dirs, this library interacts with .env file as config file, but this isn't true, we need to load environment variables through docker-compose and access it through os.getenv, we shouldn't parse .env
