### ISSUE TITLE
Кринж

### ISSUE THREAD

**Issue by evstegneych** [lubaskinc0de/clean-architecture#2]
Удаляй

**Comment by evstegneych** [comment]
Репа стремная

**Comment by steelswing** [comment]
Полностью поддерживаю аффтара данного ищью.

**Comment by lubaskinc0de** [comment]
почему?

**Comment by lubaskinc0de** [comment]
ебать ты бомжара конечно ![image](https://github.com/lubaskinc0de/clean-architecture/assets/100635212/2b9c894b-0440-4969-b195-da16954a886f)

**Comment by lubaskinc0de** [comment]
![image](https://github.com/lubaskinc0de/clean-architecture/assets/100635212/15f74a96-1251-4108-85d3-5007b52122b9)

**Comment by lubaskinc0de** [comment]
вот это структура

**Comment by evstegneych** [comment]
обиженка

**Comment by evstegneych** [comment]
закрывай репу
